server:
  port: 9001

auth0:
  issuer: "https://kids-first.auth0.com/"
  apiAudience: "https://kf-release-coord.kidsfirstdrc.org"

elasticsearch:
  host: 127.0.0.1
  port: 9200
  scheme: http
  cluster-name: elasticsearch

rollcall:
  aliases:
    - alias: file_centric
      entity: file
      type: centric
    - alias: participant_centric
      entity: participant
      type: centric
    - alias: study_centric
      entity: study
      type: centric

debug: false
