# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:11-jdk-sid

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout
    - setup_remote_docker:
        version: 18.05.0-ce
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    # Run Tests
    # - run:
    #     name: Maven Test
    #     command: |
    #       mvn test \
    #       -D spring.profiles.active=test
    - run:
        name: Maven Test
        command: |
          docker create -v /repo --name repo alpine:3.8 /bin/true
          docker cp ~/repo repo:/
          docker run --volumes-from repo -v /var/run/docker.sock:/var/run/docker.sock -w /repo circleci/openjdk:11-jdk-sid mvn test -D spring.profiles.active=test

